language: node_js
node_js: stable
sudo: required
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
script:
- npm test
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then npm run test:sl; fi
env:
  global:
  - secure: AducvbAbTCgc/4fUf3YK0Yx1WTi2GQKwrF9flS8ToUHkzqnMKfU/jI6fE3fwzs9Cx4C+RY2I43KEEmUI9B28+tuwmwrjZVEwRz/jijWAemlmwhG0GNMPvSskT4RdU7v3uLw+MibCDBw/sqM8MfUKUD07uOO8GIKJ3jjphBFPDRHIcCqRxVyqOCRSR3qdfmHjysEkDMd2YYEKB9SAshDoalvykNZlCtxBiYM5XGK0Cu0zj1JEkCmezO88Bk/NV+7VSJwtQ6EnjdctbPcLKvdYYLVG7ENCZ5MWl5M0rzz0I3GECUM5LKRpvnffs7x79g4pC+ISfE7clVCH1t+T5d29t4QOShKM7PJD2+y/NVi7JTp8oqmo74L7JirQgVqPdbAWzcp3USnvYvMpLlojQ+dACRIbktUD1q4JGJxWgs4JbYX5H3xi/hIVq2Zevux2+jqK+ezQvPfJUJIujIID6jWBEOx3+8j4eakCk1lD+20YAFN4RkaX4fjNlrOvXZZJcsDq/cd157ZAylVz+Fwgf2xI2Wb1Bp5OURVwg5+9s3TolcxEf3ZSljEe7BuwYYkROZpO0ZVB4/WIITAFO+Ry5bLsNTYHWKSJamWgdKDwCeDMatKDyxr/8D2rp9MH4rqqcDcqoREWsxv4RS0jlnVfD8xv+ZrkaHMLcWRlJhvPLIlSthA=
  - secure: prCWaetD09rJHTxcq2jBATCnLNXFutwRZTIUv6/lNfPFchVQBDIjkRAQy++7GhctYYayB2rp13yZptI1HqE4Uv70c+uHx2OcSGZoaPotSsQ1MqwRtOVzr/+nxT3Yuyur2XIk8c0ALuKZDhi5X2Ki7KZ7jYaNhBVkqbjKqnrzZb0R6zsgGT3Fg+phQT/m/a34dHdopgEPUOTeZ9R2TGjA3jr4EvXSJza3OTsPH2ho09xGg6bu5ThYYTYoDLsPHPHizZ4Gvy3cKXXBCEI0Tfa863popCIjPMfC02SQIZOAf2qbpLTpzA3hQtPAsn4q5yMAJT2cx0Lie6ZEdzAX27Rs7S3btIL/2qCoEOs8HvCVunfNPbMc74fgrT9ShHlHcs9aQQQnDmASx2ZEsLG15FABU96DgpMqlhvxaZxcX5LE+ZeaPE2HHytyLQqRnv/yM8YZ/i6/VduqNRdW0JwzhJ5U5H2QSuW+Odm6qPHDTvYF9bD97v8qEVAK39BSVfzi2g4XvCW7rDsfJzDWbiQHUXFiN56FslTvHJ7UiSQF8du8ZTC4R4MAHY+hNwmJ+vycZiYVzCx/+7yMRLtXok36NBSWCv5+4OaoJsx+kOi/2+fAc0tn0bMfjEFWUFyQrkJCIln7TueX2iZhI9Lv1sxVUC/km8ox8DYB5tyo6C60OktSoGU=
